"""
Tests for the Day 4 API contract hardening: request limits, shared
language validation, and OpenAPI documentation. Uses FastAPI's TestClient
exclusively — no real network calls, no API key required.
"""

from app.schemas import MAX_CODE_CHARS


def test_oversized_code_is_rejected_with_422(client):
    too_long = "x = 1\n" * (MAX_CODE_CHARS // 5)  # comfortably over the limit
    r = client.post("/scan", json={"code": too_long, "language": "python"})
    assert r.status_code == 422


def test_whitespace_only_code_is_rejected_with_422(client):
    r = client.post("/scan", json={"code": "   \n\t  ", "language": "python"})
    assert r.status_code == 422


def test_language_defaults_to_python_when_omitted(client):
    r = client.post("/scan", json={"code": "x = 1\n"})
    assert r.status_code == 200


def test_scan_and_review_give_consistent_language_rejection(client):
    """
    The 400 rejection for an unsupported language is generated by one
    shared helper (_require_supported_language) instead of two copies of
    the same if-statement — this test checks both endpoints still agree.
    """
    scan_resp = client.post("/scan", json={"code": "x=1", "language": "rust"})
    review_resp = client.post("/review", json={"code": "x=1", "language": "rust"})

    assert scan_resp.status_code == 400
    assert review_resp.status_code == 400
    assert "rust" in scan_resp.json()["detail"].lower()
    assert "rust" in review_resp.json()["detail"].lower()


def test_openapi_schema_includes_route_descriptions(client):
    r = client.get("/openapi.json")
    assert r.status_code == 200
    schema = r.json()

    scan_op = schema["paths"]["/scan"]["post"]
    review_op = schema["paths"]["/review"]["post"]

    assert scan_op["summary"]
    assert review_op["summary"]
    # Documented error responses should show up in the schema.
    assert "400" in scan_op["responses"]
    assert "502" in scan_op["responses"]
    assert "400" in review_op["responses"]

    # Field-level descriptions should propagate into the component schemas.
    code_field = schema["components"]["schemas"]["ScanRequest"]["properties"]["code"]
    assert "description" in code_field


def test_docs_page_loads(client):
    r = client.get("/docs")
    assert r.status_code == 200
